rm /home/rehan/git-repos/TSRA/outputs/with-short-t/first_fit/*.dat
rm /home/rehan/git-repos/TSRA/outputs/with-short-t/first_fit/*.dem
rm /home/rehan/git-repos/TSRA/outputs/with-short-t/first_fit/*.eps
rm /home/rehan/git-repos/TSRA/outputs/with-short-t/best_fit/*.dat
rm /home/rehan/git-repos/TSRA/outputs/with-short-t/best_fit/*.dem
rm /home/rehan/git-repos/TSRA/outputs/with-short-t/best_fit/*.eps
rm /home/rehan/git-repos/TSRA/outputs/with-short-t/worst_fit/*.dat
rm /home/rehan/git-repos/TSRA/outputs/with-short-t/worst_fit/*.dem
rm /home/rehan/git-repos/TSRA/outputs/with-short-t/worst_fit/*.eps

rm /home/rehan/git-repos/TSRA/outputs/with-long-t/first_fit/*.dat
rm /home/rehan/git-repos/TSRA/outputs/with-long-t/first_fit/*.dem
rm /home/rehan/git-repos/TSRA/outputs/with-long-t/first_fit/*.eps
rm /home/rehan/git-repos/TSRA/outputs/with-long-t/best_fit/*.dat
rm /home/rehan/git-repos/TSRA/outputs/with-long-t/best_fit/*.dem
rm /home/rehan/git-repos/TSRA/outputs/with-long-t/best_fit/*.eps
rm /home/rehan/git-repos/TSRA/outputs/with-long-t/worst_fit/*.dat
rm /home/rehan/git-repos/TSRA/outputs/with-long-t/worst_fit/*.dem
rm /home/rehan/git-repos/TSRA/outputs/with-long-t/worst_fit/*.eps
