rm /home/rehan/ResearchProject-HETERO/lena-extension/code/TS-VMPA_v2.1/outputs/experimentforMultiplePool/with-short-t/final/first-fit/*.dat
rm /home/rehan/ResearchProject-HETERO/lena-extension/code/TS-VMPA_v2.1/outputs/experimentforMultiplePool/with-short-t/final/first-fit/*.dem
rm /home/rehan/ResearchProject-HETERO/lena-extension/code/TS-VMPA_v2.1/outputs/experimentforMultiplePool/with-short-t/final/first-fit/*.eps
rm /home/rehan/ResearchProject-HETERO/lena-extension/code/TS-VMPA_v2.1/outputs/experimentforMultiplePool/with-short-t/final/best-fit/*.dat
rm /home/rehan/ResearchProject-HETERO/lena-extension/code/TS-VMPA_v2.1/outputs/experimentforMultiplePool/with-short-t/final/best-fit/*.dem
rm /home/rehan/ResearchProject-HETERO/lena-extension/code/TS-VMPA_v2.1/outputs/experimentforMultiplePool/with-short-t/final/best-fit/*.eps
rm /home/rehan/ResearchProject-HETERO/lena-extension/code/TS-VMPA_v2.1/outputs/experimentforMultiplePool/with-short-t/final/worst-fit/*.dat
rm /home/rehan/ResearchProject-HETERO/lena-extension/code/TS-VMPA_v2.1/outputs/experimentforMultiplePool/with-short-t/final/worst-fit/*.dem
rm /home/rehan/ResearchProject-HETERO/lena-extension/code/TS-VMPA_v2.1/outputs/experimentforMultiplePool/with-short-t/final/worst-fit/*.eps

rm /home/rehan/ResearchProject-HETERO/lena-extension/code/TS-VMPA_v2.1/outputs/experimentforMultiplePool/with-long-t/final/first-fit/*.dat
rm /home/rehan/ResearchProject-HETERO/lena-extension/code/TS-VMPA_v2.1/outputs/experimentforMultiplePool/with-long-t/final/first-fit/*.dem
rm /home/rehan/ResearchProject-HETERO/lena-extension/code/TS-VMPA_v2.1/outputs/experimentforMultiplePool/with-long-t/final/first-fit/*.eps
rm /home/rehan/ResearchProject-HETERO/lena-extension/code/TS-VMPA_v2.1/outputs/experimentforMultiplePool/with-long-t/final/best-fit/*.dat
rm /home/rehan/ResearchProject-HETERO/lena-extension/code/TS-VMPA_v2.1/outputs/experimentforMultiplePool/with-long-t/final/best-fit/*.dem
rm /home/rehan/ResearchProject-HETERO/lena-extension/code/TS-VMPA_v2.1/outputs/experimentforMultiplePool/with-long-t/final/best-fit/*.eps
rm /home/rehan/ResearchProject-HETERO/lena-extension/code/TS-VMPA_v2.1/outputs/experimentforMultiplePool/with-long-t/final/worst-fit/*.dat
rm /home/rehan/ResearchProject-HETERO/lena-extension/code/TS-VMPA_v2.1/outputs/experimentforMultiplePool/with-long-t/final/worst-fit/*.dem
rm /home/rehan/ResearchProject-HETERO/lena-extension/code/TS-VMPA_v2.1/outputs/experimentforMultiplePool/with-long-t/final/worst-fit/*.eps
